version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/api-server
    overwrite: yes

permissions:
  - object: /home/ubuntu
    pattern: '**'
    owner: ubuntu
    group: ubuntu

hooks:
 BeforeInstall:
   - location: scripts/init.sh
     runas: ubuntu
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ubuntu
