service: team-matcher-api

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: ap-northeast-2

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /

