name: deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.15.0]
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: create env file
        working-directory: .
        run:
          touch .env.production
          cat << EOF >> .env.production
          ${{ secrets.ENV }}
          EOF
          ls

      - name: zip distributions
        run: zip -r api.zip ./*

      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      #s3,codeDeploy 경로와 이름 알맞게 입력
      - name: upload to S3
        run: aws s3 cp --region ap-northeast-2 ./api.zip s3://team-matcher-bucket/api-server/

      - name: deploy with AWS codeDeploy
        run: aws deploy create-deployment
          --application-name team-matcher-codedeploy
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name deploy-group
          --s3-location bucket=team-matcher-bucket,bundleType=zip,key=api-server/api.zip